# Generated by Django 6.0.4 on 2026-04-25 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('calories_per_100g', models.FloatField()),
                ('proteins_per_100g', models.FloatField()),
                ('fats_per_100g', models.FloatField()),
                ('carbs_per_100g', models.FloatField()),
                ('price_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='nutrition.category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('activity_level', models.CharField(choices=[('low', 'Низкая'), ('light', 'Лёгкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=10)),
                ('goal', models.CharField(choices=[('lose', 'Похудение'), ('maintain', 'Поддержание'), ('gain', 'Набор массы')], max_length=10)),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.product')),
                ('ration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.ration')),
            ],
        ),
    ]
