# Generated by Django 6.0.4 on 2026-05-27 16:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(default='🥗', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='#28a745', max_length=7, verbose_name='Цвет')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория продуктов',
                'verbose_name_plural': 'Категории продуктов',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rationitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rationitem',
            name='ration',
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('calories', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Калории (на 100г)')),
                ('proteins', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Белки (г на 100г)')),
                ('carbohydrates', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Углеводы (г на 100г)')),
                ('fats', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Жиры (г на 100г)')),
                ('fiber', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Клетчатка (г на 100г)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/', verbose_name='Изображение')),
                ('is_api_data', models.BooleanField(default=False, verbose_name='Данные из API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='nutrition.foodcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], default='breakfast', max_length=20, verbose_name='Тип приёма пищи')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество (г)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='nutrition.fooditem', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись в дневнике',
                'verbose_name_plural': 'Записи в дневнике',
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)], verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1, verbose_name='Пол')),
                ('weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)], verbose_name='Вес (кг)')),
                ('height', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='Рост (см)')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Сидячий образ жизни'), ('light', 'Лёгкая активность (1-3 дня/нед)'), ('moderate', 'Умеренная активность (3-5 дней/нед)'), ('active', 'Высокая активность (6-7 дней/нед)'), ('very_active', 'Очень высокая активность')], default='moderate', max_length=20, verbose_name='Уровень активности')),
                ('goal', models.CharField(choices=[('lose', 'Похудение'), ('maintain', 'Поддержание веса'), ('gain', 'Набор массы')], default='maintain', max_length=10, verbose_name='Цель')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)], verbose_name='Вес (кг)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись веса',
                'verbose_name_plural': 'Записи веса',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Ration',
        ),
        migrations.DeleteModel(
            name='RationItem',
        ),
    ]
