# Generated by Django 6.0.6 on 2026-06-15 13:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_foodcategory_remove_product_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('emoji', models.CharField(default='🍽️', max_length=10, verbose_name='Эмодзи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='weightlog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weightlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_calorie_goal',
            field=models.FloatField(blank=True, null=True, verbose_name='Дневная норма калорий'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Малоподвижный'), ('light', 'Лёгкая активность'), ('moderate', 'Умеренная активность'), ('active', 'Высокая активность'), ('very_active', 'Очень высокая активность')], default='moderate', max_length=20, verbose_name='Уровень активности'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='female', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('lose', 'Похудение'), ('maintain', 'Поддержание веса'), ('gain', 'Набор массы')], default='maintain', max_length=20, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Рост (см)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('daily_budget', models.FloatField(verbose_name='Дневной бюджет (руб.)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бюджет питания',
                'verbose_name_plural': 'Бюджеты питания',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('calories', models.FloatField(verbose_name='Калории на 100г')),
                ('protein', models.FloatField(default=0, verbose_name='Белки на 100г')),
                ('carbs', models.FloatField(default=0, verbose_name='Углеводы на 100г')),
                ('fat', models.FloatField(default=0, verbose_name='Жиры на 100г')),
                ('emoji', models.CharField(default='🍽️', max_length=10, verbose_name='Эмодзи')),
                ('price_per_100g', models.FloatField(blank=True, null=True, verbose_name='Цена за 100г (руб.)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='nutrition.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], default='breakfast', max_length=20, verbose_name='Приём пищи')),
                ('amount_grams', models.FloatField(verbose_name='Количество (г)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='nutrition.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Запись дневника',
                'verbose_name_plural': 'Записи дневника',
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.DeleteModel(
            name='FoodCategory',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='MealLog',
        ),
        migrations.DeleteModel(
            name='WeightLog',
        ),
    ]
